### ISSUE TITLE
Permission (ACL)

### ISSUE THREAD

**Issue by patricksebastien** [pauloamgomes/CockpitCMS-Moderation#32]
Hi sorry to use issue to ask for support, I am not sure where to put the permission (ACL) for Moderation, I want a specific group to have permission to unpublish pages.

```
groups:
  my-custom-group:
    moderation:
      publish: true
      draft: true
      unpublish: true
```

Is there a UI for that?
